- name: Copy images
  copy:
    src: "{{ item.local_path }}/{{ item.file }}.iso"
    dest: "/var/isos/{{ item.file }}.iso"
    remote_src: no
  tags:
    - addimage

- name: Copy Kickstarts
  copy:
    src: "{{ item.local_path }}/{{ item.kickstart }}"
    dest: "/var/ftp/pub/ks/{{ item.kickstart }}"
    remote_src: no
  tags:
    - addimage

- name: Create image network boot directories
  file:
    path: "/var/lib/tftpboot/networkboot/{{ item.file }}"
    state: directory
  tags:
    - addimage

- name: Create image ftp directories
  file:
    path: "/var/ftp/pub/{{ item.file }}"
    state: directory
  tags:
    - addimage

- name: Create image mount directories
  file:
    path: "/iso_image/{{ item.file }}"
    state: directory
  tags:
    - addimage

- name: Mount images
  ansible.posix.mount:
    path: /iso_image/{{ item.file }}
    src: /var/isos/{{ item.file }}.iso
    fstype: iso9660
    opts: ro,noauto
    state: mounted
  tags:
    - addimage

- name: Copy images to FTP
  copy:
    src: "/iso_image/{{ item.file }}/"
    dest: "/var/ftp/pub/{{ item.file }}/"
    remote_src: yes
  tags:
    - addimage

- name: Copy image PXE kernel modules to TFTP
  copy:
    src: "/var/ftp/pub/{{ item.file }}/images/pxeboot/initrd.img"
    dest: "/var/lib/tftpboot/networkboot/{{ item.file }}/"
    remote_src: yes
  tags:
    - addimage

- name: Copy image PXE kernel to TFTP
  copy:
    src: "/var/ftp/pub/{{ item.file }}/images/pxeboot/vmlinuz"
    dest: "/var/lib/tftpboot/networkboot/{{ item.file }}/"
    remote_src: yes
  tags:
    - addimage

- name: Configure PXE Boot Menu
  blockinfile:
    path: /var/lib/tftpboot/pxelinux.cfg/default
    block: |
      default menu.c32
      prompt 1
      timeout 600
      menu title PXE Image Menu
  tags:
    - bootmenu

- name: Add Images to PXE Boot Menu
  blockinfile:
    path: /var/lib/tftpboot/pxelinux.cfg/default
    marker: ""
    insertafter: EOF
    block: |
      # Start - Menu item for {{ item.menu_name }}
      label Install {{ item.menu_name }}
      kernel /networkboot/{{ item.file }}/vmlinuz
      append initrd=/networkboot/{{ item.file }}/initrd.img inst.repo=ftp://{{ item.server_address }}/pub/{{ item.file }} inst.ks=ftp://{{ item.server_address }}/pub/ks/{{ item.kickstart }}
      # End - Menu item for {{ item.menu_name }}
  tags:
    - bootmenu

- name: Unmount images
  ansible.posix.mount:
    path: "/iso_image/{{ item.file }}"
    state: unmounted
  tags:
    - addimage

- name: Remove iso directory
  file:
    path: "/var/isos/"
    state: absent
  tags:
    - addimage